import { Metadata } from "next";
import { AppLayout as Layout } from "@/components/AppLayout";
import PlannerClient from "./PlannerClient";

export const metadata: Metadata = {
  title: "AI Travel Planner | Jemeka Tours",
  description: "Get a customized travel itinerary generated by our AI travel planner.",
};

export default function PlannerPage() {
  return (
    <Layout>
      <PlannerClient />
    </Layout>
  );
}
